on: [push]

jobs:
    jbang:
      runs-on: ubuntu-latest
      name: A job to run jbang
      steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: jbang
        uses: maxandersen/jbang-action@master
        with:
          script: createissue.java
          args: "my world"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
